<?xml version="1.0" ?> 
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (IDPERSONA?,PERS_CENT_CODIGO?,CED_NOMBRE?,PERS_DEPT_CODIGO?,DEP_NOMBRE?)+>
  <!ELEMENT IDPERSONA (#PCDATA)>
  <!ELEMENT PERS_CENT_CODIGO (#PCDATA)>
  <!ELEMENT CED_NOMBRE (#PCDATA)>
  <!ELEMENT PERS_DEPT_CODIGO (#PCDATA)>
  <!ELEMENT DEP_NOMBRE (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <IDPERSONA>1</IDPERSONA>
    <PERS_CENT_CODIGO>0E01</PERS_CENT_CODIGO>
    <CED_NOMBRE>FACULTAD DE BIOLOG&#205;A</CED_NOMBRE>
    <PERS_DEPT_CODIGO>E0A8</PERS_DEPT_CODIGO>
    <DEP_NOMBRE>BIOLOG&#205;A CELULAR E HISTOLOG&#205;A</DEP_NOMBRE>
  </DATA_RECORD>
</main>
