<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (TESI_CODIGO,IDPERSONAUTOR?,TESI_TITULOTESIS?,TESI_PREMIO?,TESI_MENCIONEURO?,TESI_FECHALECTURA?,TESI_UNIV_NOMBRE?,TESI_AREA_CODIGOTOB?,TESI_AREA_CODIGOTOP?,TESI_ESTU_ESTUDIOENT?,TESI_ESTU_ESTUDIOSAL?,TESI_UNAR_CODIGO?,TESI_UNCA_CODIGO?,TESI_UNES_CODIGO?,TESI_UNAR_CODIGO2?,TESI_UNCA_CODIGO2?,TESI_UNES_CODIGO2?)+>
  <!ELEMENT TESI_CODIGO (#PCDATA)>
  <!ELEMENT IDPERSONAUTOR (#PCDATA)>
  <!ELEMENT TESI_TITULOTESIS (#PCDATA)>
  <!ELEMENT TESI_PREMIO (#PCDATA)>
  <!ELEMENT TESI_MENCIONEURO (#PCDATA)>
  <!ELEMENT TESI_FECHALECTURA (#PCDATA)>
  <!ELEMENT TESI_UNIV_NOMBRE (#PCDATA)>
  <!ELEMENT TESI_AREA_CODIGOTOB (#PCDATA)>
  <!ELEMENT TESI_AREA_CODIGOTOP (#PCDATA)>
  <!ELEMENT TESI_ESTU_ESTUDIOENT (#PCDATA)>
  <!ELEMENT TESI_ESTU_ESTUDIOSAL (#PCDATA)>
  <!ELEMENT TESI_UNAR_CODIGO (#PCDATA)>
  <!ELEMENT TESI_UNCA_CODIGO (#PCDATA)>
  <!ELEMENT TESI_UNES_CODIGO (#PCDATA)>
  <!ELEMENT TESI_UNAR_CODIGO2 (#PCDATA)>
  <!ELEMENT TESI_UNCA_CODIGO2 (#PCDATA)>
  <!ELEMENT TESI_UNES_CODIGO2 (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <TESI_CODIGO>10000586</TESI_CODIGO>
    <IDPERSONAUTOR>2157</IDPERSONAUTOR>
    <TESI_TITULOTESIS>EL AN&#193;LISIS DE CORRESPONDENCIAS M&#218;LTIPLES EN ECOLOG&#205;A DESCRIPTIVA M&#201;TODOS, PROGRAMAS Y APLICACIONES.&#13;&#10;DOCTOR: JOS&#201; ANTONIO PALAZ&#211;N FERRANDO</TESI_TITULOTESIS>
    <TESI_PREMIO>N</TESI_PREMIO>
    <TESI_MENCIONEURO>N</TESI_MENCIONEURO>
    <TESI_FECHALECTURA>1990/07/13 00:00:00</TESI_FECHALECTURA>
    <TESI_UNIV_NOMBRE></TESI_UNIV_NOMBRE>
    <TESI_AREA_CODIGOTOB></TESI_AREA_CODIGOTOB>
    <TESI_AREA_CODIGOTOP></TESI_AREA_CODIGOTOP>
    <TESI_ESTU_ESTUDIOENT></TESI_ESTU_ESTUDIOENT>
    <TESI_ESTU_ESTUDIOSAL></TESI_ESTU_ESTUDIOSAL>
    <TESI_UNAR_CODIGO></TESI_UNAR_CODIGO>
    <TESI_UNCA_CODIGO></TESI_UNCA_CODIGO>
    <TESI_UNES_CODIGO></TESI_UNES_CODIGO>
    <TESI_UNAR_CODIGO2></TESI_UNAR_CODIGO2>
    <TESI_UNCA_CODIGO2></TESI_UNCA_CODIGO2>
    <TESI_UNES_CODIGO2></TESI_UNES_CODIGO2>
  </DATA_RECORD>
</main>
