<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (TESI_CODIGO,TESI_DNIAUTOR?,TESI_TITULOTESIS?,TESI_PREMIO?,TESI_MENCIONEURO?,TESI_FECHALECTURA?,TESI_UNIV_NOMBRE?,TESI_AREA_CODIGOTOB?,TESI_AREA_CODIGOTOP?,TESI_ESTU_ESTUDIOENT?,TESI_ESTU_ESTUDIOSAL?,TESI_UNAR_CODIGO?,TESI_UNCA_CODIGO?,TESI_UNES_CODIGO?,TESI_UNAR_CODIGO2?,TESI_UNCA_CODIGO2?,TESI_UNES_CODIGO2?)+>
  <!ELEMENT TESI_CODIGO (#PCDATA)>
  <!ELEMENT TESI_DNIAUTOR (#PCDATA)>
  <!ELEMENT TESI_TITULOTESIS (#PCDATA)>
  <!ELEMENT TESI_PREMIO (#PCDATA)>
  <!ELEMENT TESI_MENCIONEURO (#PCDATA)>
  <!ELEMENT TESI_FECHALECTURA (#PCDATA)>
  <!ELEMENT TESI_UNIV_NOMBRE (#PCDATA)>
  <!ELEMENT TESI_AREA_CODIGOTOB (#PCDATA)>
  <!ELEMENT TESI_AREA_CODIGOTOP (#PCDATA)>
  <!ELEMENT TESI_ESTU_ESTUDIOENT (#PCDATA)>
  <!ELEMENT TESI_ESTU_ESTUDIOSAL (#PCDATA)>
  <!ELEMENT TESI_UNAR_CODIGO (#PCDATA)>
  <!ELEMENT TESI_UNCA_CODIGO (#PCDATA)>
  <!ELEMENT TESI_UNES_CODIGO (#PCDATA)>
  <!ELEMENT TESI_UNAR_CODIGO2 (#PCDATA)>
  <!ELEMENT TESI_UNCA_CODIGO2 (#PCDATA)>
  <!ELEMENT TESI_UNES_CODIGO2 (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <TESI_CODIGO>10000008</TESI_CODIGO>
    <TESI_DNIAUTOR>27463780</TESI_DNIAUTOR>
    <TESI_TITULOTESIS>CARACTERISTICAS MATERNAS Y TEMPERAMENTO EN LA INFANCIA</TESI_TITULOTESIS>
    <TESI_PREMIO></TESI_PREMIO>
    <TESI_MENCIONEURO></TESI_MENCIONEURO>
    <TESI_FECHALECTURA>1996/12/14 00:00:00</TESI_FECHALECTURA>
    <TESI_UNIV_NOMBRE></TESI_UNIV_NOMBRE>
    <TESI_AREA_CODIGOTOB>735</TESI_AREA_CODIGOTOB>
    <TESI_AREA_CODIGOTOP></TESI_AREA_CODIGOTOP>
    <TESI_ESTU_ESTUDIOENT></TESI_ESTU_ESTUDIOENT>
    <TESI_ESTU_ESTUDIOSAL>005000000</TESI_ESTU_ESTUDIOSAL>
    <TESI_UNAR_CODIGO>61</TESI_UNAR_CODIGO>
    <TESI_UNCA_CODIGO>02</TESI_UNCA_CODIGO>
    <TESI_UNES_CODIGO></TESI_UNES_CODIGO>
    <TESI_UNAR_CODIGO2></TESI_UNAR_CODIGO2>
    <TESI_UNCA_CODIGO2></TESI_UNCA_CODIGO2>
    <TESI_UNES_CODIGO2></TESI_UNES_CODIGO2>
  </DATA_RECORD>
  
</main>
